### ISSUE TITLE
Filtering (#shorts)

### ISSUE THREAD

**Issue by konopielko** [listenbox/community#10]
It would be cool if you could filter the videos based on length or title - some channels don’t provide playlists for their podcast series and they post other stuff I might not be interested in

**Comment by MtndaleRedneck** [comment]
@meoyawn Can this please be tackled next 🙏🥺? Drives me crazy daily when all the YouTube shorts gets mixed in with the regular videos.

**Comment by MtndaleRedneck** [comment]
Any updates on this???

**Comment by meoyawn** [comment]
@MtndaleRedneck thanks for pinging me

there's no way to to tell if a video is a short or not using Listenbox refresh methods (that avoid being detected and banned by youtube)

I just made Listenbox skip all videos under 60 seconds, please let me know if anyone still gets shorts in their podcasts

Thanks everybody for patience

**Comment by MtndaleRedneck** [comment]
Thank you!!! The Shorts were driving me crazy.
