### ISSUE TITLE
Odysee videos

### ISSUE THREAD

**Issue by meoyawn** [listenbox/community#12]
totally possible to do now, check out this `ld+json`:

```
view-source:https://odysee.com/@AlphaNerd:8/the-absolute-state-of-twitter:7
```

**Comment by fessacchiotto** [comment]
I tried this link but doesn’t look to work…
https://odysee.com/@QuantumRhino:9/Secrets-of-the-Federal-Reserve-%282000%29:e?r=FpE91vVJu6WeiVz1RyiBaxSDFwD6ygZA

**Comment by meoyawn** [comment]
yep, this is not implemented yet

**Comment by meoyawn** [comment]
use `--force-generic` to play odysee https://github.com/yt-dlp/yt-dlp/issues/7251

**Comment by meoyawn** [comment]
> I tried this link but doesn’t look to work… https://odysee.com/@QuantumRhino:9/Secrets-of-the-Federal-Reserve-%282000%29:e?r=FpE91vVJu6WeiVz1RyiBaxSDFwD6ygZA

Odysee videos are playing now https://listenbox.app/i/HLSGr59GOx8s
