### ISSUE TITLE
Chapter support

### ISSUE THREAD

**Issue by konopielko** [listenbox/community#9]
It would be cool if you could add chapter support to the feeds (that have the chapters on youtube) as this is one of the features you lose when you switch to listenbox and is quite useful:
https://podcasters.apple.com/support/2482-using-chapters-on-apple-podcasts

**Comment by CookieyedCodes** [comment]
100% I would like this at that I am trying to push pocketcasts to convert timetags to chapters too 😅

**Comment by MtndaleRedneck** [comment]
> 100% I would like this at that I am trying to push pocketcasts to convert timetags to chapters too 😅

Listenbox is seemingly dead. There's been no updates in months. Bunch of issues that are showing as planned for close to a year. Shorts being mixed into my podcast feeds are driving me crazy. @meoyawn

**Comment by CookieyedCodes** [comment]
> > 100% I would like this at that I am trying to push pocketcasts to convert timetags to chapters too 😅
> 
> Listenbox is seemingly dead. There's been no updates in months. Bunch of issues that are showing as planned for close to a year. Shorts being mixed into my podcast feeds are driving me crazy. @meoyawn

And yet I have gotten a reply via email support(few months back), their was icon updates recently (tho that might have been because of the dark theaming of my browser) & they have replayed to a person on twitter in the past month, I sent them a tweet earlier to inquire about their reasoning why the free plan went from 50 to 5, it's still functional so not really dead in my view at least 🤔 (hopefully I can convince pocketcasts to do the timetag thing tho if anything)

**Comment by MtndaleRedneck** [comment]
> > > 100% I would like this at that I am trying to push pocketcasts to convert timetags to chapters too 😅
> > 
> > Listenbox is seemingly dead. There's been no updates in months. Bunch of issues that are showing as planned for close to a year. Shorts being mixed into my podcast feeds are driving me crazy. @meoyawn
> 
> And yet I have gotten a reply via email support(few months back), their was icon updates recently (tho that might have been because of the dark theaming of my browser) & they have replayed to a person on twitter in the past month, I sent them a tweet earlier to inquire about their reasoning why the free plan went from 50 to 5, it's still functional so not really dead in my view at least 🤔 (hopefully I can convince pocketcasts to do the timetag thing tho if anything)

I've gotten a response from @meoyawn when I DMed him a few weeks ago. Yet there hasn't been any actual updates in months. So it's seemingly somewhat on life support. It works for now, but no actual updates but being worked on. None of the feature requests marked as planned have been implemented.

**Comment by CookieyedCodes** [comment]
Eh at least its not dead yet, the problem with apps like this is the more people know the more likely it will be shutdown, long may it last 😅

**Comment by MtndaleRedneck** [comment]
@CookieyedCodes talk of the devil! @meoyawn just updated this https://github.com/listenbox/community/issues/2

**Comment by oddtoddy** [comment]
I must be in the minority, I actually like the shorts showing up in my feeds 🤣

**Comment by CookieyedCodes** [comment]
> I must be in the minority, I actually like the shorts showing up in my feeds 🤣

I don't mind shorts but ya their should be an option to exclude them, as I would prefer them not to be their in most feeds 😉

**Comment by MtndaleRedneck** [comment]
> > I must be in the minority, I actually like the shorts showing up in my feeds 🤣
> 
> I don't mind shorts but ya their should be an option to exclude them, as I would prefer them not to be their in most feeds 😉

I'd be OK with it being an option. But as it is right now it drives me crazy. I already watched the video!! Why do I need to keep getting 60 second snippets of the video??? I use YouTube Revanced and got rid of the Shorts tab entirely in the YouTube app.

**Comment by MtndaleRedneck** [comment]
@meoyawn Any chance we can get this?

**Comment by meoyawn** [comment]
> @meoyawn Any chance we can get this?

absolutely. I plan to implement this. No ETA

**Comment by meoyawn** [comment]
chapter support is now live at https://listenbox.app, please let me know if it doesn't work for you

**Comment by CookieyedCodes** [comment]
@meoyawn what type of chapters are spefically supported, just so I'm aware & can push pocket casts to support them if they don't 😅

**Comment by meoyawn** [comment]
> @meoyawn what type of chapters are spefically supported, just so I'm aware & can push pocket casts to support them if they don't 😅

this mechanism https://youtu.be/YEYnVE-vunI

**Comment by CookieyedCodes** [comment]
@meoyawn ah so it's embedded MP3 chapters & only on the audio feed just testing with a new episode in the listen later feed (actually not sure dose pocketcasts support video - podcast embedded chapters might be good too add it everywhere to make it more interoperable & future proof if you can, I'll inquire with them but I get it if that's more complicated, thanks for adding it tho ☺️🤔🤔

**Comment by CookieyedCodes** [comment]
Ya just tried with a listen later audio feed & it didn't convert the time tag to pocketcasts hmmmmm

**Comment by meoyawn** [comment]
@CookieyedCodes which platform? They mention that they don't support m4a chapters on Android https://support.pocketcasts.com/knowledge-base/chapters/#htoc-android

Listenbox episode on iOS:
![Photo 3553](https://github.com/listenbox/community/assets/1594148/9be1dc1f-bab5-4772-8e8e-2198a491715c)

**Comment by CookieyedCodes** [comment]
Ah I'm on android, I'll push them to try support m4a then, that should be related to the player dependency 😅, which might support m4a now 🤔 , I think it's exo player
